# Site settings
title: The House of Hades
email: blog@hades.name
description: >
  I am hades, a software engineer. This is the site about all the things
  I found too boring not to write about.
url: "https://hades.github.io" # the base hostname & protocol for your site
twitter_username: dr_lepper
github_username:  hades
permalink: "/:year/:month/:title"

# Build settings
markdown: kramdown
highlighter: pygments

media_prefix: '/media'
